# Generated by Django 5.0.3 on 2024-05-06 11:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ponumber', models.IntegerField()),
                ('orderdata', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 11, 5, 30, 265021))),
                ('items', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('buy', 'Buy'), ('on_road', 'On road'), ('delivered', 'Delivered')], max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
