# Generated by Django 5.0.3 on 2024-05-06 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderdata',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 11, 17, 23, 476593)),
        ),
    ]
