# Generated by Django 5.0.3 on 2024-05-06 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorder_deleted_alter_purchaseorder_orderdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderdata',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 15, 1, 30, 28013)),
        ),
    ]
