# Generated by Django 5.0.3 on 2024-05-06 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchaseorder_orderdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='orderdata',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ponumber',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=200),
        ),
    ]
