# Generated by Django 5.0.3 on 2024-05-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_remove_purchaseorder_orderdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
