# Generated by Django 5.0.3 on 2024-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(default='0', max_length=4, unique=True),
        ),
    ]
