# Generated by Django 5.0.3 on 2024-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_alter_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
